spring.application.name=ehms
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/ehms?useSSL=false&serverTimezone=UTC
spring.datasource.username=hms_user
spring.datasource.password=Hms@12345   
